{"filter":false,"title":"test_invalid_user_name_exception.py","tooltip":"/git_practice/ib_miniprojects_backend/auth_service/tests/presenters/test_invalid_user_name_exception.py","undoManager":{"mark":-1,"position":-1,"stack":[]},"ace":{"folds":[],"scrolltop":0,"scrollleft":0,"selection":{"start":{"row":4,"column":17},"end":{"row":4,"column":17},"isBackwards":false},"options":{"guessTabSize":true,"useWrapMode":false,"wrapToView":true},"firstLineState":0},"timestamp":1593429713453,"hash":"549e86e43602e6d13e730438ca57736d7fa301aa"}